### ISSUE TITLE
Converted imu(s) 0 entries into the rosbag.

### ISSUE THREAD

**Issue by AdamAsh2019** [PetWorm/kitti_to_rosbag_for_vio#1]
hi, thanks for making your work public, i try to run your code by the instruction on original kitti2rosbag, but something weird happended

Warning: no timestamp for this entry!
Converted image(s) 285 entries into the rosbag.
Converted imu(s) 0 entries into the rosbag.

**Comment by PetWorm** [comment]
sorry for i just notice this msg.
did you solve this problem ?


or you can check if you use the right cmd to run it, especially the path of dataset.
 an example is as below:

rosrun kitti_to_rosbag kitti_rosbag_converter YOUR_DATA_PATH/2011_09_26 YOUR_DATA_PATH/2011_09_26/2011_09_26_drive_0036_extract YOUR_RESULTS_PATH/xxx.bag

**Comment by songming1995** [comment]
Warning: no timestamp for this entry!
Converted image(s) 160 entries into the rosbag.
Converted imu(s) 0 entries into the rosbag.
